// src/app/contact/contact.component.ts
import { AfterViewInit, Component, HostListener, OnInit, ViewChild } from '@angular/core';
import { CheckViewPortService } from '../shared/services/check-view-port.service';
import Typewriter from 't-writer.js';
@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss'],
})
export class ContactComponent implements OnInit, AfterViewInit {
  @ViewChild('contactTypeWriter') contactTypeWriter; 
  isTitleVisible: any;
  isTitleVisibleCounter: boolean;
  constructor(private checkViewPortService: CheckViewPortService) {}

  ngOnInit(): void {}

  ngAfterViewInit(): void {
    this.typeWrite();
  }

  typeWrite() {
    const target2 = this.contactTypeWriter.nativeElement;
    console.log(target2);
    const writer2 = new Typewriter(target2, {
      loop: false,
      typeColor: 'white',
      animateCursor: true,
      cursorColor: 'white',
      typeSpeed: 40,
      deleteSpeed:0
    });

    this.isTitleVisible = writer2
      .type('cd Contact Me')
      .queueClearText()
      .type('Contact Me');
  }

  @HostListener('window:scroll', ['$event']) // for window scroll events
  onScroll(event) {
    const inViewPort = this.checkViewPortService.IsElementInViewPort(this.contactTypeWriter);
    if(!this.isTitleVisibleCounter && inViewPort) {
      console.log('skill title is visible');
      this.isTitleVisibleCounter = true;
      this.isTitleVisible.start();
    } 
    if(!inViewPort) {
      this.isTitleVisibleCounter = false;
    }
  }
}

<div fxLayoutAlign="center">
  <form class="contactContainer">
    <h1 #contactTypeWriter id="contactTypeWriter">$</h1>
    <div gdColumns="1 1fr" gdGap="14px" animateElement="fadeInLeft" speed="fast" delay="600" aos>
      <div style="position: absolute; left: -5000px;">
        <input type="checkbox" name="ultimate_chiffon_pinstriped_dolphin" value="1" tabindex="-1" autocomplete="off">
      </div>
      <mat-form-field appearance="fill" class="name">
          <mat-label [ngStyle]=
          "{'color': nameValidation.touched && nameValidation.errors?.required ? 
            'red' : 'white'}">Name</mat-label>
          <input matInput #nameValidation="ngModel" [(ngModel)]="username" name="username" required autocomplete="off" /> 
      </mat-form-field>
      <mat-form-field appearance="fill" class="email">
          <mat-label [ngStyle]=
            "{'color': emailValidation.touched && 
              (emailValidation.errors?.required || emailValidation.errors?.pattern) ? 
              'red' : 'white'}" >Email</mat-label>
          <input matInput #emailValidation="ngModel" 
            [(ngModel)]="email" name="email" 
            pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required autocomplete="off" />
      </mat-form-field>
      <mat-form-field appearance="fill" class="message">
          <mat-label>Message</mat-label>
          <textarea matInput [(ngModel)]="message" name="message" rows="5" cols="50" style="resize: none;" autocomplete="off" ></textarea>
      </mat-form-field>
      <div class="submitButton">
        <button mat-button (click)="sendMessage()">Submit</button>
      </div>
    </div>
  </form>
</div>

// src/components/contact.tsx
import React, { useState } from 'react';
import { Typewriter } from 'react-simple-typewriter'

export const ContactComponent: React.FC = () => {
    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [message, setMessage] = useState('');
  
    const sendMessage = () => {
      // Implement your logic to send the message here
      console.log('Message sent:', { username, email, message });
    };

    return(
      <div className="">
        <h1 className="text-2xl">
            <Typewriter
                words={['$Contact Me']}
                loop={1}
                cursor
                cursorStyle='|'
                typeSpeed={30}
                deleteSpeed={50}
                delaySpeed={1000}          
              />
        </h1>
        <form className="contactContainer flex justify-center mt-10">  
          <div className="grid grid-cols-1 gap-4">
            <div className="hidden">
              <input
                type="checkbox"
                name="ultimate_chiffon_pinstriped_dolphin"
                value="1"
                tabIndex={-1}
                autoComplete="off"
              />
            </div>
            <div className="w-full">
              <label className="text-white">Name</label>
              <input
                className="w-full bg-white"
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                required
                autoComplete="off"
              />
            </div>
            <div className="w-full">
              <label className="text-white">Email</label>
              <input
                className="w-full bg-white"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$"
                required
                autoComplete="off"
              />
            </div>
            <div className="w-full">
              <label className="text-white">Message</label>
              <textarea
                className="w-full bg-white resize-none"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                rows={5}
                cols={50}
                autoComplete="off"
              ></textarea>
            </div>
            <div className="text-center">
              <button
                className="text-xl text-white px-4 py-2 rounded hover:underline"
                onClick={sendMessage}
                type="button"
              >
                Submit
              </button>
            </div>
          </div>
        </form>
      </div>
    );
  };
  
  export default ContactComponent;
